#usage ./exp.sh <task> <nosw/nnosw>
#python rnn_seq2seq_gru.py $1 B-3 3 nosw
#python rnn_seq2seq_gru.py $1 B-1 3 nosw
python rnn_seq2seq_gru.py $1 A-3 3 nosw
python rnn_seq2seq_gru.py $1 A-2 3 nosw
python rnn_seq2seq_gru.py $1 C-3 3 nosw
python rnn_seq2seq_gru.py $1 C-1 3 nosw
python rnn_seq2seq_gru.py $1 B-3 4 nosw
python rnn_seq2seq_gru.py $1 B-1 4 nosw
python rnn_seq2seq_gru.py $1 A-3 4 nosw
python rnn_seq2seq_gru.py $1 A-2 4 nosw
python rnn_seq2seq_gru.py $1 C-3 4 nosw
python rnn_seq2seq_gru.py $1 C-1 4 nosw
python rnn_seq2seq_gru.py $1 B-3 5 nosw
python rnn_seq2seq_gru.py $1 B-1 5 nosw
python rnn_seq2seq_gru.py $1 A-3 5 nosw
python rnn_seq2seq_gru.py $1 A-2 5 nosw
python rnn_seq2seq_gru.py $1 C-3 5 nosw
python rnn_seq2seq_gru.py $1 C-1 5 nosw
python rnn_seq2seq_gru.py $1 B-3 6 nosw
python rnn_seq2seq_gru.py $1 B-1 6 nosw
python rnn_seq2seq_gru.py $1 A-3 6 nosw
python rnn_seq2seq_gru.py $1 A-2 6 nosw
python rnn_seq2seq_gru.py $1 C-3 6 nosw
python rnn_seq2seq_gru.py $1 C-1 6 nosw